FROM golang:1.23-alpine

ENV SERVER_PORT=5000
ENV PG_URL=postgresql://k0fanov36:k0fanov36@db:5432/hackchange2024
ENV JWT_ACCESS_SECRET=access_secret
ENV JWT_REFRESH_SECRET=refresh_secret

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]